version: "3.8"

services:
  webtop:
    build: .
    container_name: webtop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - CUSTOM_USER=user
      - PASSWORD=strong-pass
    volumes:
      - ./webtop-config:/config
      - ./data:/data
    ports:
      - "127.0.0.1:3333:3001"
      - "127.0.0.1:2222:22"
    shm_size: "1gb"
    restart: unless-stopped
    ulimits:
      core: 0
